name Windows-RDP

on workflow_dispatch

jobs
  build

    runs-on windows-latest
    timeout-minutes 999999999999

    steps
    - name Download Ngrok.
      run 
        Invoke-WebRequest httpsbin.equinox.ioc4VmDzA7iaHbngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest httpsraw.githubusercontent.comDinhPhucwindows-rdpmainstart.bat -OutFile start.bat
        Invoke-WebRequest httpsraw.githubusercontent.comDinhPhucwindows-rdpmainwallpaper.png -OutFile wallpaper.png
        Invoke-WebRequest httpsraw.githubusercontent.comDinhPhucwindows-rdpmainwallpaper.bat -OutFile wallpaper.bat
        Invoke-WebRequest httpsraw.githubusercontent.comDinhPhucwindows-rdpmainloop.bat -OutFile loop.bat
    - name Download Launcher.
      run 
        Invoke-WebRequest httpsraw.githubusercontent.comDinhPhucwindows-rdpmainlauncherNode.js.lnk -OutFile Node.js.lnk
        Invoke-WebRequest httpsraw.githubusercontent.comDinhPhucwindows-rdpmainlauncherVisual%20Studio%202019.lnk -OutFile Visual Studio 2019.lnk
        Invoke-WebRequest httpsgithub.comDinhPhucwindows-rdprawmainlauncherGanti%20Password.exe -OutFile Ganti Password.exe
    - name Extract Ngrok File.
      run Expand-Archive ngrok.zip
    - name Connect Ngrok.
      run .ngrokngrok.exe authtoken $EnvNGROK_AUTH_TOKEN
      env
        NGROK_AUTH_TOKEN ${{ secrets.NGROK_AUTH_TOKEN }}
    - name Action Access RDP.
      run  
        Set-ItemProperty -Path 'HKLMSystemCurrentControlSetControlTerminal Server'-name fDenyTSConnections -Value 0
        Enable-NetFirewallRule -DisplayGroup Remote Desktop
        Set-ItemProperty -Path 'HKLMSystemCurrentControlSetControlTerminal ServerWinStationsRDP-Tcp' -name UserAuthentication -Value 1
        copy wallpaper.png Dawallpaper.png
        copy wallpaper.bat Dawallpaper.bat
        copy Node.js.lnk CUsersPublicDesktopNode.js.lnk
        copy Visual Studio 2019.lnk CUsersPublicDesktopVisual Studio 2019.lnk
        copy Ganti Password.exe CUsersPublicDesktopGanti Password.exe
    - name Making tunnels
      run Start-Process Powershell -ArgumentList '-Noexit -Command .ngrokngrok.exe tcp --region ap 3389'
    - name Connect RDP CPU 2 Core - 7GB Ram - 256 SSD.
      run cmd c start.bat
    - name Successful implementation! You can close the tab now.
      run cmd c loop.bat
